name: WhatsApp Automation Bot

on:
  schedule:
    - cron: '*/30 * * * *'
  repository_dispatch:
    types: [trigger-whatsapp-bot]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: npm install firebase node-fetch # Instalando o fetch explicitamente

      - name: Run
        run: node bot-envio.js
