name: WhatsApp Automation Bot

on:
  schedule:
    - cron: '*/30 * * * *' # Backup a cada 30 min
  repository_dispatch: # PERMITE DISPARO IMEDIATO PELO APP
    types: [trigger-whatsapp-bot]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install firebase

      - name: Run WhatsApp Bot
        run: node bot-envio.js
